dist: trusty
sudo: false
# addons:
#   firefox: latest
#   apt:
#     packages:
#       - google-chrome-stable
language: node_js
node_js:
  - 10
before_install:
  # - export CHROME_BIN=/usr/bin/google-chrome
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
before_script:
  - git diff --exit-code # make sure that package-lock.json didn't change
  - ./packages/blob-reader/scripts/update-fixtures.sh
script:
  - travis_retry npm test && codecov
  - npm run build
  # - travis_retry npm run e2e
deploy:
  - provider: script
    script: npm run package
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "$GH_DEPLOY"
    file_glob: true
    file: "out/*.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run release
    skip_cleanup: true
    on:
      tags: true
