sudo: false
language: node_js
node_js:
  - 4
  - 6 # if you change this, change `node: 6` in `deploy` below as well
cache:
  directories:
    - node_modules
after_success:
  - npm run package-all
deploy:
  - provider: releases
    api_key: "$GH_DEPLOY"
    file_glob: true
    file: "out/*.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run release
    on:
      branch: master
      tags: true
      node: 6
