sudo: false
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
# TODO unpin npm once this is fixed: https://github.com/npm/npm/issues/14042
before_install:
  - npm install -g npm@3.10.7
before_deploy:
  - npm run package-all
deploy:
  - provider: releases
    api_key: "$GH_DEPLOY"
    file_glob: true
    file: "out/*.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run release
    on:
      branch: master
      tags: true
