sudo: false
language: node_js
node_js:
  - 4.0
  - 4
  - 6
after_success:
  - npm run package-all
deploy:
  - provider: releases
    api_key: "$GH_DEPLOY"
    file_glob: true
    file: "out/*.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run release
    on:
      branch: master
      tags: true
