dist: trusty
sudo: false
addons:
  firefox: latest
  apt:
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 8
cache:
  yarn: true
# Use npm > 4 to fix https://github.com/npm/npm/issues/14042
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - git diff --exit-code # make sure that yarn.lock didn't change
  - ./packages/blob-reader/scripts/update-fixtures.sh
  - npm run package
script:
  - travis_retry npm test
deploy:
  - provider: releases
    api_key: "$GH_DEPLOY"
    file_glob: true
    file: "out/*.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run release
    skip_cleanup: true
    on:
      branch: master
      tags: true
