sudo: false
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
# Use npm > 4 to fix https://github.com/npm/npm/issues/14042
before_install:
  - npm install -g npm@latest
before_script:
  - ./packages/blob-reader/scripts/update-fixtures.sh
before_deploy:
  - npm run package-all
deploy:
  - provider: releases
    api_key: "$GH_DEPLOY"
    file_glob: true
    file: "out/*.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: npm run release
    on:
      branch: master
      tags: true
