// @OctoLinkerResolve(https://hub.docker.com/_/php/)
FROM php:php:5.6-apache

// @OctoLinkerResolve(https://hub.docker.com/_/ubuntu/)
FROM        ubuntu:16.04 AS base

// @OctoLinkerResolve(<root>/docker/docker-entrypoint.sh)
ENTRYPOINT ["docker-entrypoint.sh"]
